// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayProjectify.ProductService.Data;

#nullable disable

namespace PlayProjectify.ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260211125659_ProductSeedData")]
    partial class ProductSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PlayProjectify.ProductService.Models.Entites.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4e9ef00-fc2b-4fde-8900-c3c69016ea18"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc),
                            Description = "Electronic devices and gadgets.",
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7e42e4ab-ea84-4055-8f73-f4cefd3998fe"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc),
                            Description = "Clothing, shoes, and accessories for men and women.",
                            Name = "Fashion",
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d61d02f9-160f-439a-8f2d-d7dc87da4d99"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc),
                            Description = "Printed and digital books across all genres.",
                            Name = "Books",
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6cf79ab1-e24d-411f-a467-629807552051"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc),
                            Description = "Fitness equipment, outdoor gear, and sports accessories.",
                            Name = "Sports & Outdoors",
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c7f2295b-9ec3-4d52-9c0a-727350255749"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc),
                            Description = "Children’s toys, board games, and entertainment items.",
                            Name = "Toys & Games",
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PlayProjectify.ProductService.Models.Entites.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("e4e9ef00-fc2b-4fde-8900-c3c69016ea18"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "6.5-inch display, 128GB storage, 5G support",
                            Name = "Smartphone X12",
                            Price = 799m,
                            StockQuantity = 30,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("e4e9ef00-fc2b-4fde-8900-c3c69016ea18"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "15-inch laptop with 16GB RAM and 1TB SSD",
                            Name = "Laptop Pro 15",
                            Price = 1499m,
                            StockQuantity = 15,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("e4e9ef00-fc2b-4fde-8900-c3c69016ea18"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "Noise cancelling over-ear headphones",
                            Name = "Bluetooth Headphones",
                            Price = 199m,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("e4e9ef00-fc2b-4fde-8900-c3c69016ea18"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "Fitness tracking smartwatch with heart rate monitor",
                            Name = "Smartwatch Active",
                            Price = 249m,
                            StockQuantity = 40,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("e4e9ef00-fc2b-4fde-8900-c3c69016ea18"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "Waterproof speaker with deep bass",
                            Name = "Portable Bluetooth Speaker",
                            Price = 99m,
                            StockQuantity = 60,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("c7f2295b-9ec3-4d52-9c0a-727350255749"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "High-speed RC car with rechargeable battery",
                            Name = "Remote Control Car",
                            Price = 59m,
                            StockQuantity = 25,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("c7f2295b-9ec3-4d52-9c0a-727350255749"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "500-piece creative building block set",
                            Name = "Building Blocks Set",
                            Price = 49m,
                            StockQuantity = 40,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("c7f2295b-9ec3-4d52-9c0a-727350255749"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "Multiplayer strategy board game for ages 10+",
                            Name = "Board Game: Strategy Wars",
                            Price = 39m,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("c7f2295b-9ec3-4d52-9c0a-727350255749"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "Scenic landscape puzzle for adults",
                            Name = "Puzzle 1000 Pieces",
                            Price = 29m,
                            StockQuantity = 35,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("c7f2295b-9ec3-4d52-9c0a-727350255749"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "Superhero action figure 5-pack",
                            Name = "Action Figure Set",
                            Price = 79m,
                            StockQuantity = 18,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("6cf79ab1-e24d-411f-a467-629807552051"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "Foldable treadmill with digital display",
                            Name = "Treadmill Home Runner",
                            Price = 899m,
                            StockQuantity = 5,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("d61d02f9-160f-439a-8f2d-d7dc87da4d99"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "A Handbook of Agile Software Craftsmanship",
                            Name = "Clean Code",
                            Price = 45m,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("d61d02f9-160f-439a-8f2d-d7dc87da4d99"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "Your Journey to Mastery",
                            Name = "The Pragmatic Programmer",
                            Price = 50m,
                            StockQuantity = 80,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("7e42e4ab-ea84-4055-8f73-f4cefd3998fe"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "100% cotton, breathable fabric",
                            Name = "Men's Casual T-Shirt",
                            Price = 19m,
                            StockQuantity = 120,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("7e42e4ab-ea84-4055-8f73-f4cefd3998fe"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "Classic fit blue denim jacket",
                            Name = "Women's Denim Jacket",
                            Price = 79m,
                            StockQuantity = 45,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("7e42e4ab-ea84-4055-8f73-f4cefd3998fe"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight shoes for everyday training",
                            Name = "Running Sneakers",
                            Price = 99m,
                            StockQuantity = 60,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("7e42e4ab-ea84-4055-8f73-f4cefd3998fe"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc),
                            Description = "Genuine leather slim wallet",
                            Name = "Leather Wallet",
                            Price = 35m,
                            StockQuantity = 75,
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 56, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PlayProjectify.ProductService.Models.Entites.Product", b =>
                {
                    b.HasOne("PlayProjectify.ProductService.Models.Entites.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PlayProjectify.ProductService.Models.Entites.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
