// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayProjectify.ProductService.Data;

#nullable disable

namespace PlayProjectify.ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260211124918_CategorySeedData")]
    partial class CategorySeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PlayProjectify.ProductService.Models.Entites.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4e9ef00-fc2b-4fde-8900-c3c69016ea18"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc),
                            Description = "Electronic devices and gadgets.",
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7e42e4ab-ea84-4055-8f73-f4cefd3998fe"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc),
                            Description = "Clothing, shoes, and accessories for men and women.",
                            Name = "Fashion",
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d61d02f9-160f-439a-8f2d-d7dc87da4d99"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc),
                            Description = "Printed and digital books across all genres.",
                            Name = "Books",
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6cf79ab1-e24d-411f-a467-629807552051"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc),
                            Description = "Fitness equipment, outdoor gear, and sports accessories.",
                            Name = "Sports & Outdoors",
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c7f2295b-9ec3-4d52-9c0a-727350255749"),
                            CreatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc),
                            Description = "Children’s toys, board games, and entertainment items.",
                            Name = "Toys & Games",
                            UpdatedAt = new DateTime(2026, 2, 11, 13, 49, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PlayProjectify.ProductService.Models.Entites.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PlayProjectify.ProductService.Models.Entites.Product", b =>
                {
                    b.HasOne("PlayProjectify.ProductService.Models.Entites.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PlayProjectify.ProductService.Models.Entites.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
